In [86]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [3]:
path = 'data\\'
df = pd.read_csv(path + '202112-divvy-tripdata.csv')

In [4]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,46F8167220E4431F,electric_bike,2021-12-07 15:06:07,2021-12-07 15:13:42,Laflin St & Cullerton St,13307,Morgan St & Polk St,TA1307000130,41.854833,-87.663660,41.871969,-87.650965,member
1,73A77762838B32FD,electric_bike,2021-12-11 03:43:29,2021-12-11 04:10:23,LaSalle Dr & Huron St,KP1705001026,Clarendon Ave & Leland Ave,TA1307000119,41.894405,-87.632331,41.967968,-87.650001,casual
2,4CF42452054F59C5,electric_bike,2021-12-15 23:10:28,2021-12-15 23:23:14,Halsted St & North Branch St,KA1504000117,Broadway & Barry Ave,13137,41.899357,-87.648522,41.937582,-87.644098,member
3,3278BA87BF698339,classic_bike,2021-12-26 16:16:10,2021-12-26 16:30:53,Halsted St & North Branch St,KA1504000117,LaSalle Dr & Huron St,KP1705001026,41.899390,-87.648545,41.894877,-87.632326,member
4,6FF54232576A3B73,electric_bike,2021-12-30 11:31:05,2021-12-30 11:51:21,Leavitt St & Chicago Ave,18058,Clark St & Drummond Pl,TA1307000142,41.895579,-87.682024,41.931248,-87.644336,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
247535,847431F3D5353AB7,electric_bike,2021-12-12 13:36:55,2021-12-12 13:56:08,Canal St & Madison St,13341,NaN,NaN,41.882289,-87.639752,41.890000,-87.610000,casual
247536,CF407BBC3B9FAD63,electric_bike,2021-12-06 19:37:50,2021-12-06 19:44:51,Canal St & Madison St,13341,Kingsbury St & Kinzie St,KA1503000043,41.882123,-87.640053,41.889106,-87.638862,member
247537,60BB69EBF5440E92,electric_bike,2021-12-02 08:57:04,2021-12-02 09:05:21,Canal St & Madison St,13341,Dearborn St & Monroe St,TA1305000006,41.881956,-87.639955,41.880254,-87.629603,member
247538,C414F654A28635B8,electric_bike,2021-12-13 09:00:26,2021-12-13 09:14:39,Lawndale Ave & 16th St,362.0,NaN,NaN,41.860000,-87.720000,41.850000,-87.710000,member
247539,37AC57E34B2E7E97,classic_bike,2021-12-13 08:45:32,2021-12-13 08:49:09,Michigan Ave & Jackson Blvd,TA1309000002,Dearborn St & Monroe St,TA1305000006,41.877850,-87.624080,41.881320,-87.629521,member

In [5]:
df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

## Create a column called “ride_length.”

In [7]:
df['ride_length'] = pd.to_datetime(df['ended_at']) - pd.to_datetime(df['started_at'])

In [8]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
0,46F8167220E4431F,electric_bike,2021-12-07 15:06:07,2021-12-07 15:13:42,Laflin St & Cullerton St,13307,Morgan St & Polk St,TA1307000130,41.854833,-87.663660,41.871969,-87.650965,member,0 days 00:07:35
1,73A77762838B32FD,electric_bike,2021-12-11 03:43:29,2021-12-11 04:10:23,LaSalle Dr & Huron St,KP1705001026,Clarendon Ave & Leland Ave,TA1307000119,41.894405,-87.632331,41.967968,-87.650001,casual,0 days 00:26:54
2,4CF42452054F59C5,electric_bike,2021-12-15 23:10:28,2021-12-15 23:23:14,Halsted St & North Branch St,KA1504000117,Broadway & Barry Ave,13137,41.899357,-87.648522,41.937582,-87.644098,member,0 days 00:12:46
3,3278BA87BF698339,classic_bike,2021-12-26 16:16:10,2021-12-26 16:30:53,Halsted St & North Branch St,KA1504000117,LaSalle Dr & Huron St,KP1705001026,41.899390,-87.648545,41.894877,-87.632326,member,0 days 00:14:43
4,6FF54232576A3B73,electric_bike,2021-12-30 11:31:05,2021-12-30 11:51:21,Leavitt St & Chicago Ave,18058,Clark St & Drummond Pl,TA1307000142,41.895579,-87.682024,41.931248,-87.644336,member,0 days 00:20:16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247535,847431F3D5353AB7,electric_bike,2021-12-12 13:36:55,2021-12-12 13:56:08,Canal St & Madison St,13341,NaN,NaN,41.882289,-87.639752,41.890000,-87.610000,casual,0 days 00:19:13
247536,CF407BBC3B9FAD63,electric_bike,2021-12-06 19:37:50,2021-12-06 19:44:51,Canal St & Madison St,13341,Kingsbury St & Kinzie St,KA1503000043,41.882123,-87.640053,41.889106,-87.638862,member,0 days 00:07:01
247537,60BB69EBF5440E92,electric_bike,2021-12-02 08:57:04,2021-12-02 09:05:21,Canal St & Madison St,13341,Dearborn St & Monroe St,TA1305000006,41.881956,-87.639955,41.880254,-87.629603,member,0 days 00:08:17
247538,C414F654A28635B8,electric_bike,2021-12-13 09:00:26,2021-12-13 09:14:39,Lawndale Ave & 16th St,362.0,NaN,NaN,41.860000,-87.720000,41.850000,-87.710000,member,0 days 00:14:13
247539,37AC57E34B2E7E97,classic_bike,2021-12-13 08:45:32,2021-12-13 08:49:09,Michigan Ave & Jackson Blvd,TA1309000002,Dearborn St & Monroe St,TA1305000006,41.877850,-87.624080,41.881320,-87.629521,member,0 days 00:03:37

## Create a column called “day_of_week,”

In [31]:
# Monday  = 0 , Sunday = 6
df['day_of_week'] = pd.to_datetime(df['started_at']).dt.dayofweek + 2

In [32]:
df.describe()

,start_lat,start_lng,end_lat,end_lng,ride_length,day_of_week
count,247540.000000,247540.000000,247396.000000,247396.000000,247540,247540.000000
mean,41.896822,-87.649813,41.896917,-87.649981,0 days 00:14:31.409477256,4.927612
std,0.049759,0.033691,0.049730,0.033747,0 days 01:56:54.526309431,1.805024
min,41.640000,-87.840000,41.480000,-87.850000,0 days 00:00:00,2.000000
25%,41.879434,-87.667178,41.879809,-87.667429,0 days 00:04:58,4.000000
50%,41.895644,-87.644135,41.895748,-87.644140,0 days 00:08:26,5.000000
75%,41.928712,-87.629560,41.928712,-87.629634,0 days 00:14:44,6.000000
max,42.070000,-87.520000,42.070000,-87.520000,21 days 02:40:33,8.000000

## Calculate the mean, max of ride_length

In [33]:
mean_ride_length = df['ride_length'].mean()
mean_ride_length

Timedelta('0 days 00:14:31.409477256')

In [34]:
max_ride_length = df['ride_length'].max()
max_ride_length

Timedelta('21 days 02:40:33')

## Calculate the mode of day of week

In [35]:
# Monday  = 0 , Sunday = 6
mode_day_of_week = df['day_of_week'].mode() 
mode_day_of_week

0    5
dtype: int64

In [36]:
df['day_of_week'].value_counts()

5    47767
4    44742
6    42438
2    30218
7    30156
3    28386
8    23833
Name: day_of_week, dtype: int64

In [38]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week
0,46F8167220E4431F,electric_bike,2021-12-07 15:06:07,2021-12-07 15:13:42,Laflin St & Cullerton St,13307,Morgan St & Polk St,TA1307000130,41.854833,-87.663660,41.871969,-87.650965,member,0 days 00:07:35,3
1,73A77762838B32FD,electric_bike,2021-12-11 03:43:29,2021-12-11 04:10:23,LaSalle Dr & Huron St,KP1705001026,Clarendon Ave & Leland Ave,TA1307000119,41.894405,-87.632331,41.967968,-87.650001,casual,0 days 00:26:54,7
2,4CF42452054F59C5,electric_bike,2021-12-15 23:10:28,2021-12-15 23:23:14,Halsted St & North Branch St,KA1504000117,Broadway & Barry Ave,13137,41.899357,-87.648522,41.937582,-87.644098,member,0 days 00:12:46,4
3,3278BA87BF698339,classic_bike,2021-12-26 16:16:10,2021-12-26 16:30:53,Halsted St & North Branch St,KA1504000117,LaSalle Dr & Huron St,KP1705001026,41.899390,-87.648545,41.894877,-87.632326,member,0 days 00:14:43,8
4,6FF54232576A3B73,electric_bike,2021-12-30 11:31:05,2021-12-30 11:51:21,Leavitt St & Chicago Ave,18058,Clark St & Drummond Pl,TA1307000142,41.895579,-87.682024,41.931248,-87.644336,member,0 days 00:20:16,5

In [27]:
# s = pd.date_range('2022-3-1', '2022-03-03', freq='D').to_series()
# s.dt.dayofweek

## Calculate the average ride_length for members and casual riders

In [168]:
df.groupby('member_casual')['ride_length'].agg(lambda x: x.mean())

member_casual
casual   0 days 00:23:29.657446442
member   0 days 00:11:00.296346497
Name: ride_length, dtype: timedelta64[ns]

In [147]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week
0,46F8167220E4431F,electric_bike,2021-12-07 15:06:07,2021-12-07 15:13:42,Laflin St & Cullerton St,13307,Morgan St & Polk St,TA1307000130,41.854833,-87.663660,41.871969,-87.650965,member,0 days 00:07:35,3
1,73A77762838B32FD,electric_bike,2021-12-11 03:43:29,2021-12-11 04:10:23,LaSalle Dr & Huron St,KP1705001026,Clarendon Ave & Leland Ave,TA1307000119,41.894405,-87.632331,41.967968,-87.650001,casual,0 days 00:26:54,7
2,4CF42452054F59C5,electric_bike,2021-12-15 23:10:28,2021-12-15 23:23:14,Halsted St & North Branch St,KA1504000117,Broadway & Barry Ave,13137,41.899357,-87.648522,41.937582,-87.644098,member,0 days 00:12:46,4
3,3278BA87BF698339,classic_bike,2021-12-26 16:16:10,2021-12-26 16:30:53,Halsted St & North Branch St,KA1504000117,LaSalle Dr & Huron St,KP1705001026,41.899390,-87.648545,41.894877,-87.632326,member,0 days 00:14:43,8
4,6FF54232576A3B73,electric_bike,2021-12-30 11:31:05,2021-12-30 11:51:21,Leavitt St & Chicago Ave,18058,Clark St & Drummond Pl,TA1307000142,41.895579,-87.682024,41.931248,-87.644336,member,0 days 00:20:16,5

## Calculate the average ride_length for users by day_of_week

In [176]:
df.groupby(['day_of_week', 'member_casual'])['ride_length'].agg(lambda x: x.mean())

day_of_week  member_casual
2            casual          0 days 00:23:51.413810940
             member          0 days 00:10:50.809117189
3            casual          0 days 00:22:23.111396057
             member          0 days 00:10:45.715898315
4            casual          0 days 00:23:10.980941704
             member          0 days 00:10:28.349374228
5            casual          0 days 00:22:22.166375337
             member          0 days 00:10:56.712202609
6            casual          0 days 00:21:52.950440018
             member          0 days 00:10:56.441765025
7            casual          0 days 00:22:40.140009021
             member          0 days 00:11:51.849247548
8            casual          0 days 00:29:36.842242503
             member          0 days 00:11:57.468433359
Name: ride_length, dtype: timedelta64[ns]

## Calculate the number of rides for users by day_of_week

In [172]:
df.groupby(['day_of_week', 'member_casual'])['ride_id'].count()

day_of_week  member_casual
2            casual            7733
             member           22485
3            casual            6239
             member           22147
4            casual           10704
             member           34038
5            casual           12586
             member           35181
6            casual           12954
             member           29484
7            casual           11085
             member           19071
8            casual            8437
             member           15396
Name: ride_id, dtype: int64